/**
 * In-game text in English and Bahasa Indonesia. Games call `tx(ctx, key)` so commands, banners,
 * result headlines and stat labels follow the player's language setting.
 */
const T = {
  // Generic flow
  wait: ['WAIT…', 'TUNGGU…'],
  stayStill: ['Stay still', 'Diam dulu'],
  go: ['GO!', 'MULAI!'],
  round: ['ROUND {n}', 'RONDE {n}'],
  roundOf: ['ROUND {n} / {m}', 'RONDE {n} / {m}'],
  finalRound: ['FINAL ROUND', 'RONDE TERAKHIR'],
  wins: ['{name} WINS', '{name} MENANG'],
  winsRound: ['{name} WINS THE ROUND', '{name} MENANG RONDE INI'],
  draw: ['DRAW!', 'SERI!'],
  out: ['OUT', 'KELUAR'],
  ready: ['READY…', 'SIAP…'],
  paused: ['PAUSED', 'JEDA'],
  notDetected: ['{names} NOT DETECTED', '{names} TIDAK TERDETEKSI'],
  moveIntoFrame: ['MOVE INTO FRAME', 'MASUK KE DALAM FRAME'],
  tracking: ['⚠ tracking', '⚠ tracking'],
  gameOver: ['GAME OVER', 'PERMAINAN SELESAI'],
  timeUp: ['TIME UP!', 'WAKTU HABIS!'],
  firstTo: ['First to {n}', 'Duluan {n}'],
  points: ['{n} points', '{n} poin'],
  oops: ['OOPS!', 'UPS!'],
  oopsSub: ['This game hit a problem. Try a rematch or another game.', 'Game ini mengalami masalah. Coba rematch atau game lain.'],
  starting: ['STARTING…', 'MULAI…'],
  keepPracticing: ['KEEP PRACTICING', 'TERUS BERLATIH'],
  perfectSync: ['PERFECT SYNC', 'SINKRON SEMPURNA'],
  greatSync: ['GREAT SYNC', 'SINKRON HEBAT'],
  goodSync: ['GOOD SYNC', 'SINKRON BAGUS'],
  perfectCouple: ['PERFECT COUPLE!', 'PASANGAN SEMPURNA!'],
  greatTeam: ['GREAT TEAM!', 'TIM HEBAT!'],
  niceTeam: ['Nice teamwork!', 'Kerja sama bagus!'],
  syncUp: ['Rematch and sync up!', 'Rematch dan makin kompak!'],
  inSync: ['YOU TWO ARE {p}% IN SYNC ❤️', 'KALIAN {p}% SINKRON ❤️'],
  canYouBeat: ['Can you beat me?', 'Bisa kalahkan aku?'],
  bestScore: ['Best score', 'Skor terbaik'],
  bestSync: ['Best sync', 'Sinkron terbaik'],

  // Commands
  cmdJump: ['JUMP!', 'LOMPAT!'],
  cmdSquat: ['SQUAT!', 'JONGKOK!'],
  cmdHandsUp: ['HANDS UP!', 'ANGKAT TANGAN!'],
  cmdLeft: ['LEFT!', 'KIRI!'],
  cmdRight: ['RIGHT!', 'KANAN!'],
  cmdPunch: ['PUNCH!', 'PUKUL!'],
  cmdLeanLeft: ['LEAN LEFT!', 'CONDONG KIRI!'],
  cmdLeanRight: ['LEAN RIGHT!', 'CONDONG KANAN!'],
  cmdLeftHand: ['LEFT HAND UP!', 'TANGAN KIRI NAIK!'],
  cmdRightHand: ['RIGHT HAND UP!', 'TANGAN KANAN NAIK!'],
  cmdKick: ['KICK!', 'TENDANG!'],
  cmdClap: ['CLAP!', 'TEPUK!'],
  cmdBlock: ['BLOCK!', 'TANGKIS!'],
  cmdFreeze: ['FREEZE!', 'DIAM!'],
  cmdDont: ["DON'T {x}", 'JANGAN {x}'],
  cmdMove: ['MOVE!', 'JOGET!'],
  cmdDance: ['DANCE!', 'JOGET!'],
  cmdDuck: ['DUCK!', 'MENUNDUK!'],

  // Reactions / feedback
  falseStart: ['FALSE START!', 'CURI START!'],
  gotcha: ['GOTCHA!', 'KENA JEBAK!'],
  wrong: ['✗ WRONG', '✗ SALAH'],
  tooSlow: ['TOO SLOW', 'TERLAMBAT'],
  steady: ['✓ STEADY', '✓ STABIL'],
  moved: ['MOVED!', 'BERGERAK!'],
  caught: ['CAUGHT!', 'KETAHUAN!'],
  perfect: ['PERFECT!', 'SEMPURNA!'],
  great: ['GREAT!', 'HEBAT!'],
  good: ['GOOD', 'BAGUS'],
  miss: ['MISS', 'MELESET'],
  combo: ['COMBO x{n}', 'COMBO x{n}'],
  hit: ['HIT!', 'KENA!'],
  blocked: ['BLOCKED', 'DITANGKIS'],
  dodged: ['DODGED!', 'MENGHINDAR!'],
  perfectDodge: ['PERFECT DODGE!', 'HINDARAN SEMPURNA!'],
  counter: ['COUNTER!', 'SERANGAN BALIK!'],
  critical: ['CRITICAL!', 'KRITIS!'],
  ko: ['K.O.!', 'K.O.!'],
  goal: ['GOAL!', 'GOL!'],
  saved: ['SAVED!', 'DITEPIS!'],
  missed: ['MISSED!', 'MELESET!'],
  swish: ['SWISH!', 'MASUK!'],
  boost: ['BOOST!', 'BOOST!'],
  ouch: ['OUCH!', 'ADUH!'],
  rally: ['RALLY {n}!', 'RALI {n}!'],
  locked: ['LOCKED!', 'TERKUNCI!'],
  holdIt: ['HOLD IT…', 'TAHAN…'],
  revive: ['REVIVE!', 'BANGKIT!'],
  down: ['DOWN!', 'TUMBANG!'],
  wave: ['WAVE {n}', 'GELOMBANG {n}'],
  boss: ['BOSS!', 'BOS!'],
  elite: ['ELITE WAVE', 'GELOMBANG ELIT'],
  nova: ['NOVA!', 'NOVA!'],
  novaReady: ['NOVA READY — BOTH HANDS UP!', 'NOVA SIAP — ANGKAT TANGAN BERDUA!'],
  newBest: ['NEW BEST!', 'REKOR BARU!'],
  finish: ['FINISH!', 'FINISH!'],
  lap: ['LAP {n}/{m}', 'PUTARAN {n}/{m}'],
  nitro: ['NITRO!', 'NITRO!'],
  drift: ['DRIFT!', 'DRIFT!'],
  shield: ['SHIELD!', 'PERISAI!'],
  swap: ['SWAP!', 'TUKAR!'],
  yourTurn: ['{name}’S TURN', 'GILIRAN {name}'],
  both: ['BOTH', 'BERDUA'],
  leader: ['LEADER', 'PEMIMPIN'],
  follower: ['FOLLOWER', 'PENGIKUT'],
  attacker: ['ATTACK', 'SERANG'],
  defender: ['DODGE', 'HINDAR'],
  kicker: ['KICKER', 'PENENDANG'],
  keeper: ['KEEPER', 'KIPER'],
  cpu: ['CPU', 'CPU'],
  cpuWins: ['CPU WINS', 'CPU MENANG'],
  youWin: ['YOU WIN!', 'KAMU MENANG!'],
  rest: ['REST', 'ISTIRAHAT'],
  reps: ['{n} reps', '{n} repetisi'],

  matchPose: ['MATCH THE POSE!', 'TIRU POSENYA!'],
  poseOf: ['POSE {n} / {m}', 'POSE {n} / {m}'],
  together: ['{x} TOGETHER!', '{x} BERSAMA!'],
  syncPct: ['{p}% SYNC', '{p}% SINKRON'],
  keepDancing: ['KEEP DANCING!', 'TERUS JOGET!'],
  danceNow: ['DANCE!', 'JOGET!'],
  safe: ['SAFE', 'AMAN'],
  eliminated: ['ELIMINATED!', 'TERELIMINASI!'],
  noShow: ['NO MOVE', 'TIDAK BERGERAK'],
  // Stat labels
  statAvgReaction: ['Average reaction', 'Rata-rata reaksi'],
  statBestReaction: ['Best reaction', 'Reaksi terbaik'],
  statFalseStarts: ['False starts', 'Curi start'],
  statHits: ['Hits', 'Kena'],
  statAccuracy: ['Accuracy', 'Akurasi'],
  statBestCombo: ['Best combo', 'Combo terbaik'],
  statDamage: ['Damage dealt', 'Damage diberikan'],
  statBlocks: ['Blocks', 'Tangkisan'],
  statDodges: ['Perfect dodges', 'Hindaran sempurna'],
  statRounds: ['Rounds won', 'Ronde dimenangkan'],
  statPaddleHits: ['Paddle hits', 'Pukulan raket'],
  statRally: ['Longest rally', 'Rali terpanjang'],
  statSurvived: ['Survived', 'Bertahan'],
  statCaught: ['Times caught', 'Kali ketahuan'],
  statDance: ['Dance points', 'Poin joget'],
  statSync: ['Average sync', 'Rata-rata sinkron'],
  statBestMove: ['Best move', 'Gerakan terbaik'],
  statPoses: ['Poses nailed', 'Pose berhasil'],
  statTime: ['Time', 'Waktu'],
  statDistance: ['Distance', 'Jarak'],
  statCoins: ['Coins', 'Koin'],
  statGoals: ['Goals', 'Gol'],
  statSaves: ['Saves', 'Tepisan'],
  statShots: ['Shots made', 'Tembakan masuk'],
  statReps: ['Reps', 'Repetisi'],
  statStreak: ['Best streak', 'Streak terbaik'],
  statKills: ['Zombies defeated', 'Zombie dikalahkan'],
  statWaves: ['Waves cleared', 'Gelombang dilewati'],
  statPipes: ['Pipes passed', 'Pipa dilewati'],
  statMultiplier: ['Max multiplier', 'Pengali tertinggi'],
  statCaughtItems: ['Items caught', 'Benda ditangkap'],
  statBombs: ['Bombs touched', 'Bom tersentuh'],
  statPlace: ['Finish place', 'Posisi finish'],
  statLapTime: ['Race time', 'Waktu balap'],
  statComboTeam: ['Team combo', 'Combo tim'],
  statHeld: ['Time held', 'Waktu bertahan'],
} as const;

export type TxKey = keyof typeof T;

export function tx(ctx: { lang: 'en' | 'id' }, key: TxKey, vars?: Record<string, string | number>): string {
  let s: string = T[key][ctx.lang === 'id' ? 1 : 0];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}

/** Inline bilingual string for game-specific text. */
export const L = (ctx: { lang: 'en' | 'id' }, en: string, id: string): string => (ctx.lang === 'id' ? id : en);
